version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pip setuptools --upgrade
            pip install -r requirements.txt

      - run:
          name: Docker for qvm and quilc
          command: |
#            docker run --rm -it -d -p 5555:5555 rigetti/quilc -R -p 5555
#            docker run --rm -it -d -p 5000:5000 rigetti/qvm -S -p 5000
             docker run -rm -d --name quilc rigetti/quilc -R -p 5555
             docker run --network container:quilc curl --retry 10 --retry-connrefused http://127.0.0.1:5555
             docker run -rm -d --name qvm rigetti/qvm -S -p 5000
             docker run --network container:qvm curl --retry 10 --retry-connrefused http://127.0.0.1:5000

      - restore_cache:
          keys:
            - gallery

      - run:
          name: Build tutorials
          command: |
            . venv/bin/activate
            make download
            make html

      - save_cache:
          paths:
            - ./tutorial
            - ./app
          key: gallery

  deploy:
    executor:
      name: aws-cli/default
      python-version: '3.7.2'

    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - aws-cli/setup:
          aws-region: AWS_REGION

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pip setuptools --upgrade
            pip install -r requirements.txt

      - restore_cache:
          keys:
            - gallery

      - run:
          name: Build tutorials
          command: |
            . venv/bin/activate
            make download
            make html

      - save_cache:
          paths:
            - ./tutorial
            - ./app
          key: gallery

      - deploy:
          name: Deploy to AWS
          command: |
            aws s3 sync _build/html s3://pennylane.ai/qml --delete
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /qml/*

workflows:
  workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: master

      - deploy:
          context: aws_credentials
          filters:
            branches:
              only: master
