name: update-dev
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-dev:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Merge master -> dev
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          head_to_merge: master
          target_branch: dev
          github_token: ${{ github.token }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Merge latest master branch into dev
          body: >-
            This is an automated pull request by the
            [create-pull-request](https://github.com/peter-evans/create-pull-request)
            GitHub action. This pull request is triggered automatically on changes
            to `master`, to ensure the `dev` branch remains up to date. Please verify
            everything looks okay, clean up any merge conflicts, and merge this in.
          reviewers: josh146, antalszava, thisac
          draft: false

      - name: Check output
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
